### ISSUE TITLE
Curious about the original results for three metrics in MR-Score

### ISSUE THREAD

**Issue by scorpio-nova** [dvlab-research/Mr-Ben#2]
Thanks to all the authors for this wonderful benchmark!

I am reaching out with a query regarding the MR-Score calculation formula: MR-Score = w_1 * max(0, MCC) + w_2 * Accuracy(step) + w_3 * Accuracy(reason)

I am interested in the original results for the three metrics(MCC, Accuracy(step), Accuracy(reason))
Could you please provide the specific numerical data for these metrics? I understand that this might be a lot of work, but this may help understand the models' performance thoroughly. 

Thanks very much!

**Comment by Randolph-zeng** [comment]
Hi @scorpio-nova, thanks for your issue. Indeed these sub metrics might provide another insight for the models' performance. I will update the paper and create the table for these sub metrics in the appendix soon. In the meantime, you can look for the submetrics you are interested in this json I crawled from the experiment outputs. 
[mr_scores_breakdown.json](https://github.com/user-attachments/files/16237169/mr_scores_breakdown.json)

**Comment by scorpio-nova** [comment]
Thanks for your timely response! This data works for me :)
